// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDUpsBDOEJU_XHfJ9vhePJD7KcBETZh10',
    appId: '1:985046986106:web:90c050ee8353509a4abac3',
    messagingSenderId: '985046986106',
    projectId: 'showmovies-3a304',
    authDomain: 'showmovies-3a304.firebaseapp.com',
    storageBucket: 'showmovies-3a304.firebasestorage.app',
    measurementId: 'G-WTF3LHPRDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcyF5OIolCRZjfvNhk5tORqcodGZKAMbQ',
    appId: '1:985046986106:android:cccb306700e9d3db4abac3',
    messagingSenderId: '985046986106',
    projectId: 'showmovies-3a304',
    storageBucket: 'showmovies-3a304.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL7PVbH0ib3ZJjuiCzdGXnaAjJlYYbOvI',
    appId: '1:985046986106:ios:cc0a1bdd84353ba54abac3',
    messagingSenderId: '985046986106',
    projectId: 'showmovies-3a304',
    storageBucket: 'showmovies-3a304.firebasestorage.app',
    iosBundleId: 'com.maniga.showmovies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL7PVbH0ib3ZJjuiCzdGXnaAjJlYYbOvI',
    appId: '1:985046986106:ios:cc0a1bdd84353ba54abac3',
    messagingSenderId: '985046986106',
    projectId: 'showmovies-3a304',
    storageBucket: 'showmovies-3a304.firebasestorage.app',
    iosBundleId: 'com.maniga.showmovies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDUpsBDOEJU_XHfJ9vhePJD7KcBETZh10',
    appId: '1:985046986106:web:c41534377f4626264abac3',
    messagingSenderId: '985046986106',
    projectId: 'showmovies-3a304',
    authDomain: 'showmovies-3a304.firebaseapp.com',
    storageBucket: 'showmovies-3a304.firebasestorage.app',
    measurementId: 'G-1GTRJK6ZZE',
  );
}
